baseURL = "https://alimoameri.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ali Moameri"
theme = "PaperMod"

[pagination]
pagerSize = 5


[[params.social]]
  id = "github"
  url = "https://github.com/alimoameri"

[[params.social]]
  id = "email"
  url = "moammeriali@gmail.com"

[[params.social]]
  id = "linkedin"
  url = "https://www.linkedin.com/in/ali-moameri-4345131b6/"

[[params.social]]
  id = "telegram"
  url = "https://t.me/aliinaction"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3


[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[languages]
[languages.en]
languageName = "English"
languagedirection ="ltr"
contentDir = 'content/en'


[languages.fa]
languageName = "Farsi"
languagedirection ="rtl"
title="علی معمری"
contentDir = 'content/fa'

[[languages.fa.menu.main]]
identifier = "home"
name = "خانه"
url = "/"
weight = 1

[[languages.fa.menu.main]]
identifier = "posts"
name = "پست‌ها"
url = "/posts/"
weight = 2

[[languages.fa.menu.main]]
identifier = "tags"
name = "برچسب‌ها"
url = "/tags/"
weight = 3

[[languages.fa.menu.main]]
identifier = "about"
name = "درباره"
url = "/about/"
weight = 4

[languages.fa.params]
languageCode = "fa-fa"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

# [markup]
# defaultMarkdownHandler = 'goldmark'

# [markup.goldmark.renderer]
# unsafe = true

# [markup.highlight]
# anchorLineNos      = false
# codeFences         = true # tested with true and false. Both work.
# noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
# style              = 'base16-snazzy'
# tabWidth           = 4

[params.GoogleAnalytics]
enabled = false
gtag = ""
